window.LESSONS = [
{u:"12",unit:"Surds",id:"12.1",title:"Understand and simplify surds",type:"surds",src:"Morrison & Hamshaw pp. 276–277 Ex 9.7; pp. 281–282 Ex 9.8 Q1–4",prior:["Square numbers and prime factors","Simplifying numerical roots","Index laws"],obj:["Recognise exact surd form","Simplify surds using factor pairs","Multiply and divide surds","Combine like surds"]},
{u:"12",unit:"Surds",id:"12.2",title:"Rationalise the denominator",type:"rationalise",src:"Morrison & Hamshaw pp. 282–284 Ex 9.8 Q5–7, Ex 9.9",prior:["Simplifying surds","Difference of two squares","Equivalent fractions"],obj:["Rationalise a single surd denominator","Use conjugates for binomial denominators","Simplify final exact answers"]},

{u:"13",unit:"Algebraic fractions",id:"13.1",title:"Factorise and simplify rational expressions",type:"algfrac-simplify",src:"Morrison & Hamshaw pp. 464–467 Ex 14.13–14.14",prior:["Common factors","Factorising quadratics","Cancelling numerical fractions"],obj:["Factor numerator and denominator","State excluded values where appropriate","Cancel common factors correctly"]},
{u:"13",unit:"Algebraic fractions",id:"13.2",title:"Manipulate algebraic fractions",type:"algfrac-four",src:"Morrison & Hamshaw pp. 462–463 Ex 14.12",prior:["Equivalent fractions","Lowest common multiples","Factorising expressions"],obj:["Add and subtract algebraic fractions","Multiply and divide algebraic fractions","Give fully simplified answers"]},

{u:"14",unit:"Equations",id:"14.1",title:"Construct expressions, equations and formulae",type:"forming",src:"Morrison & Hamshaw pp. 42–43 Ex 2.1",prior:["Algebraic notation","Collecting like terms","Translating words into symbols"],obj:["Form expressions from contexts","Construct linear and quadratic equations","Create formulae from relationships"]},
{u:"14",unit:"Equations",id:"14.2",title:"Solve linear equations in one unknown",type:"linear",src:"Morrison & Hamshaw p.185 Ex 6.1; pp.756–760 Ex 22.1–22.2",prior:["Inverse operations","Expanding brackets","Collecting like terms"],obj:["Solve equations with unknowns on one side","Solve equations with brackets and unknowns on both sides","Form and solve linear equations from problems"]},
{u:"14",unit:"Equations",id:"14.3",title:"Solve quadratic equations",type:"quadratic",src:"Morrison & Hamshaw p.330 Ex 10.12; p.455 Ex 14.8; pp.458–459 Ex 14.9",prior:["Factorising quadratics","Square roots","Substitution"],obj:["Solve by factorisation","Complete the square","Use the quadratic formula","Interpret exact surd solutions"]},
{u:"14",unit:"Equations",id:"14.4",title:"Solve fractional equations",type:"fractional-eq",src:"Morrison & Hamshaw p.185 Ex 6.1 Q5–7; p.330 Ex 10.12 Q2",prior:["Algebraic fractions","Lowest common multiples","Linear equations"],obj:["Clear numerical denominators","Clear linear algebraic denominators","Check solutions against restrictions"]},
{u:"14",unit:"Equations",id:"14.5",title:"Solve simultaneous linear equations",type:"simultaneous-linear",src:"Morrison & Hamshaw pp.430–439 Ex 14.1–14.2",prior:["Linear equations","Substitution","Coordinate graphs"],obj:["Solve by elimination","Solve by substitution","Interpret graphical intersections","Form simultaneous equations from contexts"]},
{u:"14",unit:"Equations",id:"14.6",title:"Linear and non-linear simultaneous equations",type:"simultaneous-nonlinear",src:"Morrison & Hamshaw p.607 Ex 18.6",prior:["Simultaneous equations","Quadratic equations","Substitution"],obj:["Substitute a linear equation into a quadratic relation","Find all valid solution pairs","Check solutions in both equations"]},
{u:"14",unit:"Equations",id:"14.7",title:"Change the subject of formulae",type:"rearrange",src:"Morrison & Hamshaw p.190 Ex 6.3; pp.765–766 Ex 22.4–22.5",prior:["Inverse operations","Factorising","Powers and roots"],obj:["Rearrange one-step and multi-step formulae","Handle the subject appearing twice","Handle powers and roots of the subject"]},

{u:"15",unit:"Inequalities",id:"15.1",title:"Represent and interpret inequalities",type:"ineq-numberline",src:"Morrison & Hamshaw p.441 Ex 14.3",prior:["Ordering numbers","Number lines","Inequality symbols"],obj:["Interpret <, >, ≤ and ≥","Represent inequalities on a number line","Write inequalities from number-line diagrams"]},
{u:"15",unit:"Inequalities",id:"15.2",title:"Construct, solve and interpret linear inequalities",type:"ineq-linear",src:"Morrison & Hamshaw p.444 Ex 14.4",prior:["Linear equations","Negative numbers","Number lines"],obj:["Solve linear inequalities","Reverse the sign when multiplying/dividing by a negative","Solve compound inequalities"]},
{u:"15",unit:"Inequalities",id:"15.3",title:"Graph linear inequalities in two variables",type:"ineq-graph",src:"Morrison & Hamshaw pp.449–452 Ex 14.5–14.6",prior:["Straight-line graphs","Coordinates","Testing points"],obj:["Draw boundary lines accurately","Use solid and dashed boundaries correctly","Shade the correct half-plane"]},
{u:"15",unit:"Inequalities",id:"15.4",title:"List inequalities defining a region",type:"ineq-region",src:"Syllabus-linked extension of Ex 14.5–14.6",prior:["Graphing inequalities","Equation of a line","Region shading"],obj:["Identify each boundary equation","Choose the correct inequality sign","Describe a region using several inequalities"]},

{u:"16",unit:"Geometry of shapes",id:"16.1",title:"Angles and geometric reasoning",type:"angles",src:"Morrison & Hamshaw pp.82–83 Ex 3.3",prior:["Angle types","Triangle and quadrilateral names","Three-letter angle notation"],obj:["Use angles at a point and on a line","Use vertically opposite angles","Use triangle and quadrilateral angle sums","Give correct geometric reasons"]},
{u:"16",unit:"Geometry of shapes",id:"16.2",title:"Angles in parallel lines",type:"parallel",src:"Morrison & Hamshaw pp.84–85 Ex 3.4",prior:["Straight-line angles","Vertically opposite angles","Parallel line notation"],obj:["Identify corresponding angles","Identify alternate angles","Use co-interior angles","Give a reason at each step"]},
{u:"16",unit:"Geometry of shapes",id:"16.3",title:"Angle properties of polygons",type:"polygons",src:"Morrison & Hamshaw pp.90–94 Ex 3.5–3.6",prior:["Triangle angle sum","Regular polygons","Exterior angles"],obj:["Find interior angle sums","Find interior and exterior angles of regular polygons","Solve problems involving irregular polygons"]},
{u:"16",unit:"Geometry of shapes",id:"16.4",title:"Line and rotational symmetry",type:"symmetry2d",src:"Morrison & Hamshaw pp.644–647 Ex 19.1–19.2",prior:["Properties of common polygons","Transformations","Circle properties"],obj:["Identify lines of symmetry","State order of rotational symmetry","Link symmetry to shape properties"]},
{u:"16",unit:"Geometry of shapes",id:"16.5",title:"Symmetry of 3D solids",type:"symmetry3d",src:"Morrison & Hamshaw pp.649–651 Ex 19.3–19.4",prior:["Names of prisms, pyramids and cones","2D symmetry","Cross-sections"],obj:["Identify planes of symmetry","Identify axes of rotational symmetry","Reason about prisms, cylinders, pyramids and cones"]},

{u:"17",unit:"Mensuration 1",id:"17.1",title:"Metric units and conversions",type:"units",src:"Morrison & Hamshaw pp.403–404 Ex 13.1 Q1–5",prior:["Metric prefixes","Multiplying by powers of ten","Area and volume units"],obj:["Convert length and mass units","Convert square and cubic units","Convert capacity and volume"]},
{u:"17",unit:"Mensuration 1",id:"17.2",title:"Perimeter and area of 2D shapes",type:"area",src:"Morrison & Hamshaw pp.198–201 Ex 7.1",prior:["Rectangle and triangle area","Algebraic substitution","Units"],obj:["Find perimeter and area of rectangles, triangles, parallelograms and trapezia","Work backwards from area","Solve compound-shape problems"]},
{u:"17",unit:"Mensuration 1",id:"17.3",title:"Circumference and area of circles",type:"circle",src:"Morrison & Hamshaw pp.204–207 Ex 7.2–7.3",prior:["Radius and diameter","Using π","Substitution"],obj:["Use C=2πr and C=πd","Use A=πr²","Give exact and rounded answers"]},
{u:"17",unit:"Mensuration 1",id:"17.4",title:"Arc length and sector area",type:"sector",src:"Morrison & Hamshaw pp.209–212 Ex 7.4",prior:["Circle formulae","Fractions of 360°","Proportion"],obj:["Find minor and major arc lengths","Find sector areas","Work backwards to find angles or radii"]},

{u:"18",unit:"Statistical measures",id:"18.1",title:"Classify and tabulate statistical data",type:"tables",src:"Morrison & Hamshaw pp.111–123 Ex 4.1, 4.2, 4.3, 4.5",prior:["Categories and frequencies","Counting accurately","Reading tables"],obj:["Classify categorical and numerical data","Complete tally and frequency tables","Complete and interpret two-way tables"]},
{u:"18",unit:"Statistical measures",id:"18.2",title:"Mean, median, mode, quartiles and spread",type:"averages",src:"Morrison & Hamshaw pp.370–371 Ex 12.1",prior:["Ordering data","Arithmetic mean","Range"],obj:["Calculate measures of centre","Calculate quartiles, range and IQR","Choose an appropriate summary measure"]},
{u:"18",unit:"Statistical measures",id:"18.3",title:"Estimate the mean from grouped data",type:"grouped-mean",src:"Morrison & Hamshaw pp.378–386 Ex 12.3–12.5",prior:["Class intervals","Midpoints","Weighted mean"],obj:["Find class midpoints","Calculate fx","Estimate the mean from grouped data"]},
{u:"18",unit:"Statistical measures",id:"18.4",title:"Identify the modal and median class",type:"modalclass",src:"Syllabus extension alongside grouped-data exercises",prior:["Grouped frequency tables","Cumulative frequency","Mode and median"],obj:["Identify the modal class","Locate the class containing the median","Explain why grouped answers are approximate"]},
{u:"18",unit:"Statistical measures",id:"18.5",title:"Read and interpret tables",type:"data-interpret",src:"Morrison & Hamshaw pp.373–374 Ex 12.2",prior:["Percentages","Averages","Frequency tables"],obj:["Extract information accurately","Compare categories and totals","Make evidence-based statements"]},
{u:"18",unit:"Statistical measures",id:"18.6",title:"Compare sets of data using measures",type:"data-compare",src:"Syllabus-linked statistical comparison practice",prior:["Mean and median","Range and IQR","Contextual interpretation"],obj:["Compare averages","Compare spread","Write balanced comparison statements"]},
{u:"18",unit:"Statistical measures",id:"18.7",title:"Restrictions on drawing conclusions",type:"data-limits",src:"Syllabus-linked interpretation practice",prior:["Samples and populations","Bias","Measures of centre"],obj:["Spot limitations in data","Distinguish association from proof","Write cautious statistical conclusions"]},

{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.1",title:"Bar charts, pie charts, pictograms and stem-and-leaf",type:"charts",src:"Morrison & Hamshaw pp.120–139 Ex 4.4, 4.7–4.10",prior:["Angles in a circle","Frequency tables","Scale reading"],obj:["Draw common statistical diagrams","Use a key and sensible scale","Interpret and compare displays"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.2",title:"Draw and interpret scatter diagrams",type:"scatter",src:"Morrison & Hamshaw pp.537–540 Ex 16.1",prior:["Coordinates","Scale choice","Bivariate data"],obj:["Plot paired data accurately","Describe the pattern","Identify outliers"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.3",title:"Positive, negative and zero correlation",type:"correlation",src:"Linked to Morrison & Hamshaw Ex 16.1",prior:["Scatter diagrams","Variables","Trend"],obj:["Classify correlation","Describe strength cautiously","Explain that correlation does not prove causation"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.4",title:"Line of best fit",type:"bestfit",src:"Linked to Morrison & Hamshaw Ex 16.1",prior:["Scatter diagrams","Straight lines","Interpolation"],obj:["Draw a sensible line of best fit","Estimate values by interpolation","Recognise unreliable extrapolation"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.5",title:"Cumulative frequency tables and diagrams",type:"cumfreq",src:"Morrison & Hamshaw pp.686–692 Ex 20.2–20.3",prior:["Grouped data","Running totals","Coordinate plotting"],obj:["Complete cumulative frequencies","Plot upper class boundaries","Draw a smooth cumulative frequency curve"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.6",title:"Median, quartiles and percentiles from cumulative frequency",type:"cumfreq-read",src:"Morrison & Hamshaw pp.686–692 Ex 20.2–20.3",prior:["Cumulative frequency curves","Quartiles","Percentages"],obj:["Read median and quartiles","Estimate percentiles","Calculate and interpret IQR"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.7",title:"Draw and interpret histograms",type:"histogram",src:"Morrison & Hamshaw pp.676–679 Ex 20.1",prior:["Grouped continuous data","Class width","Area of rectangles"],obj:["Calculate frequency density","Draw unequal-width histogram bars","Recover frequencies from a histogram"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.8",title:"Calculate with frequency density",type:"freqdensity",src:"Morrison & Hamshaw pp.676–679 Ex 20.1",prior:["Histogram area","Frequency density","Class width"],obj:["Use density = frequency ÷ class width","Find missing frequencies","Find missing class widths"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.9",title:"Infer from statistical diagrams",type:"chart-infer",src:"Morrison & Hamshaw pp.378–379 Ex 12.3 Q6–7 plus chart work",prior:["Reading scales","Averages and spread","Chart types"],obj:["Read values accurately","Make supported inferences","Avoid claims not justified by the display"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.10",title:"Compare sets of data using graphs",type:"graph-compare",src:"Syllabus-linked graph comparison practice",prior:["Median and IQR","Cumulative frequency","Histograms"],obj:["Compare centre and spread from graphs","Comment on shape and consistency","Use numerical evidence"]},
{u:"19",unit:"Statistical diagrams, graphs and charts",id:"19.11",title:"Restrictions on conclusions from graphs",type:"graph-limits",src:"Syllabus-linked interpretation practice",prior:["Misleading graphs","Sampling","Correlation"],obj:["Identify misleading scales or samples","Recognise extrapolation risk","Write qualified conclusions"]},

{u:"20",unit:"Functions",id:"20.1",title:"Functions, domain, range and notation",type:"functions",src:"Morrison & Hamshaw pp.772–773 Ex 22.6",prior:["Substitution","Mappings","Set notation"],obj:["Use f(x) notation","Evaluate functions","Identify domain and range"]},
{u:"20",unit:"Functions",id:"20.2",title:"Inverse functions",type:"inverse",src:"Morrison & Hamshaw pp.777–778 Ex 22.8",prior:["Function notation","Rearranging formulae","One-to-one mappings"],obj:["Find f⁻¹(x) algebraically","Check by composition","Interpret inverse mappings"]},
{u:"20",unit:"Functions",id:"20.3",title:"Composite functions",type:"composite",src:"Morrison & Hamshaw p.775 Ex 22.7",prior:["Function notation","Substitution","Order of operations"],obj:["Evaluate gf(x)=g(f(x))","Form composite expressions","Distinguish fg from gf"]},

{u:"21",unit:"Sets",id:"21.1",title:"Set language, notation and Venn diagrams",type:"sets",src:"Morrison & Hamshaw pp.286–295 Ex 9.10–9.13",prior:["Basic set notation","Factors and multiples","Probability language"],obj:["Use ∪, ∩, complement and subset notation","Complete two- and three-set Venn diagrams","Apply De Morgan relationships"]},

{u:"22",unit:"Proportion",id:"22.1",title:"Direct and inverse proportion",type:"proportion",src:"Morrison & Hamshaw pp.747–749 Ex 21.12",prior:["Ratio","Powers and roots","Solving equations"],obj:["Model direct proportion","Model inverse proportion","Use square, cube and root relationships","Find constants and unknown quantities"]}
];