window.STARTERS={
"12.1":["Write [[72]] as a product containing the largest square factor.","Simplify [[\\sqrt{49}]].","List the first six square numbers.","Evaluate [[3^2\\times3^4]]."],
"12.2":["Simplify [[\\sqrt{48}]].","Expand [[(x+5)(x-5)]].","Write a fraction equivalent to [[3/7]].","Simplify [[\\sqrt3\\times\\sqrt{12}]]."],
"13.1":["Factorise [[6x+18]].","Factorise [[x^2+7x+12]].","Simplify [[18/24]].","State the value excluded from [[1/(x-4)]]."],
"13.2":["Work out [[2/3+5/6]].","Factorise [[x^2-9]].","Write the reciprocal of [[3x/5]].","Find the lowest common denominator of [[1/x]] and [[1/(x+2)]]."],
"14.1":["Write 'five more than x' algebraically.","Is [[3x+2]] an expression or an equation?","Write two consecutive even integers in terms of n.","Write a formula for the area of a rectangle."],
"14.2":["Solve [[x+7=15]].","Expand [[3(x+4)]].","Simplify [[5x-2x+7]].","Solve [[4x=28]]."],
"14.3":["Factorise [[x^2+5x+6]].","Solve [[x^2=36]].","Expand [[(x+2)(x+5)]].","Write [[2x^2+7x-3=0]] in the form [[ax^2+bx+c=0]]."],
"14.4":["Find the LCM of 4 and 6.","Solve [[x/5=3]].","State the restriction on [[1/(x+1)]].","Simplify [[1/3+1/4]]."],
"14.5":["Solve [[x+y=10]] when [[x=6]].","Solve [[3x+2=17]].","Substitute [[x=4]] into [[y=2x-3]].","What do two intersecting straight-line graphs have in common at their intersection?"],
"14.6":["Factorise [[x^2-5x+6]].","Substitute [[y=x+2]] into [[x^2+y=10]].","Solve [[x^2=16]].","How many intersections can a straight line have with a circle?"],
"14.7":["Make x the subject of [[y=x+5]].","Make t the subject of [[v=u+at]] when a and u are known.","Factorise [[ax+bx]].","Undo the operation in [[y=3x-4]] to isolate x."],
"15.1":["Which is larger: [[-3]] or [[-7]]?","Translate 'at least 5' into an inequality.","What does an open circle mean on a number line?","List the integers satisfying [[1<x<5]]."],
"15.2":["Solve [[x+4<9]].","Work out [[-12\\div3]].","What happens to an inequality sign when dividing by a negative?","Represent [[x\\ge2]] in words."],
"15.3":["State the gradient of [[y=2x+3]].","Find the y-intercept of [[y=-x+5]].","Does [[(0,0)]] satisfy [[y>x-2]]?","What is the equation of the horizontal line through y=4?"],
"15.4":["Find the equation of the vertical line through [[x=3]].","Does [[(2,1)]] satisfy [[x+y\\le5]]?","What sign gives a solid boundary including the line?","Write an inequality for the region above [[y=x]]."],
"16.1":["Name an angle of [[35^\\circ]].","Find the missing angle on a straight line with [[128^\\circ]].","Find the third angle of a triangle with angles [[50^\\circ,60^\\circ]].","What is the total angle around a point?"],
"16.2":["Find the supplement of [[72^\\circ]].","State the relationship between vertically opposite angles.","What symbol shows two lines are parallel?","If corresponding angles are equal, what must be true about the lines?"],
"16.3":["Find the angle sum of a triangle.","Find the exterior angle of a regular hexagon.","How many sides does an octagon have?","Find [[360\\div8]]."],
"16.4":["State the rotational order of a square.","How many lines of symmetry does an equilateral triangle have?","Does a general parallelogram have line symmetry?","Find the smallest rotation for order 6."],
"16.5":["Name a 3D solid with two circular faces.","What 2D shape is the cross-section of a triangular prism?","Define a plane of symmetry.","State one axis of rotational symmetry of a cylinder."],
"17.1":["Convert [[3.5\\text{ m}]] to cm.","Convert [[2500\\text{ g}]] to kg.","How many cm are in 1 m?","How many cm³ are in 1 litre?"],
"17.2":["Find the area of a [[7\\times5]] rectangle.","Find the area of a triangle with base 8 and height 6.","What is the perimeter of a 4 by 9 rectangle?","State the formula for the area of a parallelogram."],
"17.3":["A circle has diameter 14 cm. Find its radius.","State the formula for circumference using r.","State the formula for area of a circle.","Find [[2\\pi(5)]]."],
"17.4":["What fraction of a circle is [[90^\\circ]]?","Find the major angle if the minor angle is [[80^\\circ]].","Write [[120/360]] in simplest form.","State the circumference of a circle of radius r."],
"18.1":["Is height discrete or continuous?","Is eye colour numerical or categorical?","Find the total frequency of 4, 7 and 9.","What is a two-way table used to classify?"],
"18.2":["Find the mean of 4,6,8.","Find the median of 9,2,5,7,3.","Find the range of 12,5,18,9.","What does IQR stand for?"],
"18.3":["Find the midpoint of 10–20.","Work out [[7\\times15]].","Find the total frequency 3+8+5.","Why is a grouped-data mean an estimate?"],
"18.4":["Which class is modal: frequencies 4,9,6,3?","Find cumulative frequencies for 3,5,4.","For 20 values, where is the median position?","What information is lost when data are grouped?"],
"18.5":["Find 25% of 80.","A row has values 6,11,3. Find its total.","What is the difference between a frequency and a percentage?","Why can percentages be fairer than counts when group sizes differ?"],
"18.6":["Which is more consistent: range 5 or range 14?","Which is larger: median 62 or 58?","Calculate [[Q_3-Q_1]] for [[Q_3=20,Q_1=8]].","Name one measure of centre and one measure of spread."],
"18.7":["What is the difference between a sample and a population?","Give one example of sampling bias.","Does correlation prove causation?","Why can a small sample be unreliable?"],
"19.1":["Find [[360\\div12]].","A category has frequency 8 out of 40. Find its fraction.","Why are bars separated on a bar chart?","What must a stem-and-leaf diagram include besides ordered leaves?"],
"19.2":["Plotting [[(3,7)]]: which coordinate is horizontal?","Choose a sensible scale for values 0–50.","What is bivariate data?","What is an outlier?"],
"19.3":["If y rises as x rises, what type of correlation may be present?","If y falls as x rises, what type of correlation may be present?","Does a steep slope automatically mean strong correlation?","Give one possible confounding variable in a real context."],
"19.4":["What is interpolation?","What is extrapolation?","Should a line of best fit join every point?","Why is extrapolation usually less reliable?"],
"19.5":["Find cumulative frequencies for 4,6,3,7.","What must the final cumulative frequency equal?","For grouped data, which class boundary is plotted?","Can a cumulative-frequency curve decrease?"],
"19.6":["For 80 values, find the median CF position.","For 80 values, find the lower quartile CF position.","Find the IQR if [[Q_1=18,Q_3=31]].","Which percentile is the upper quartile?"],
"19.7":["Find the class width of [[10\\le x<18]].","Find [[24\\div8]].","What quantity is represented by histogram bar area?","Should continuous histogram bars touch?"],
"19.8":["Rearrange [[d=f/w]] to make f the subject.","Find density when f=30 and width=10.","Find frequency when density=2.5 and width=8.","Find width when f=24 and density=3."],
"19.9":["A bar is 42 and another 31. Find the difference.","Why should graph readings sometimes be called estimates?","What must be checked before comparing two pie charts?","State one reason a graph may not justify a causal conclusion."],
"19.10":["Find the IQR if [[Q_1=12,Q_3=27]].","Which is more consistent: IQR 6 or 11?","What does a higher median suggest?","Why should comparisons use the same statistic for both groups?"],
"19.11":["What is a truncated axis?","Define extrapolation.","Why can a convenience sample be biased?","Does a graph starting above zero always mean it is wrong?"],
"20.1":["Evaluate [[3x+2]] when [[x=4]].","In a mapping, what is an input?","What is the output of [[f(x)=x^2]] when [[x=-3]]?","State the value excluded from [[1/(x-5)]]."],
"20.2":["Make x the subject of [[y=3x+2]].","What does an inverse function do?","Is [[f^{-1}(x)]] the same as [[1/f(x)]]?","Why must an inverse function be one-to-one?"],
"20.3":["If [[f(x)=x+1]], find [[f(3)]].","Which function acts first in [[g(f(x))]]?","Evaluate [[2(x+3)]] when x=4.","Why should brackets be used when substituting an expression?"],
"21.1":["What does [[A\\cup B]] mean?","What does [[A\\cap B]] mean?","What does [[A']] mean?","If 20 students are in A and 8 are in A∩B, why should the overlap not be counted twice?"],
"22.1":["Simplify the ratio 12:18.","If y doubles when x doubles, what type of relationship might this suggest?","Evaluate [[3^2]] and [[\\sqrt{49}]].","What symbol means 'is proportional to'?"]
};