window.STARTER_ANSWERS={
"12.1":["[[72=36\\times2]] (or another correct square-factor decomposition).","7.","1, 4, 9, 16, 25, 36.","[[3^6=729]]."],
"12.2":["[[4\\sqrt3]].","[[x^2-25]].","For example [[6/14]].","6."],
"13.1":["[[6(x+3)]].","[[(x+3)(x+4)]].","[[3/4]].","[[x\\ne4]]."],
"13.2":["[[3/2]].","[[(x-3)(x+3)]].","[[5/(3x)]].","[[x(x+2)]]."],
"14.1":["[[x+5]].","Expression.","[[2n,2n+2]].","[[A=lw]]."],
"14.2":["8.","[[3x+12]].","[[3x+7]].","7."],
"14.3":["[[(x+2)(x+3)]].","[[x=\\pm6]].","[[x^2+7x+10]].","Already in standard form; [[a=2,b=7,c=-3]]."],
"14.4":["12.","15.","[[x\\ne-1]].","[[7/12]]."],
"14.5":["[[y=4]].","[[x=5]].","5.","They share the same coordinate pair, the simultaneous solution."],
"14.6":["[[(x-2)(x-3)]].","[[x^2+x+2=10]].","[[x=\\pm4]].","0, 1 or 2."],
"14.7":["[[x=y-5]].","[[t=(v-u)/a]].","[[x(a+b)]].","Add 4, then divide by 3."],
"15.1":["-3.","[[x\\ge5]].","The endpoint is not included.","2, 3, 4."],
"15.2":["[[x<5]].","-4.","Reverse it.","x is greater than or equal to 2."],
"15.3":["2.","5.","Yes, because [[0>-2]].","[[y=4]]."],
"15.4":["[[x=3]].","Yes, because [[2+1\\le5]].","[[\\le]] or [[\\ge]].","[[y>x]] (or [[y\\ge x]] if boundary included)."],
"16.1":["Acute.","[[52^\\circ]].","[[70^\\circ]].","[[360^\\circ]]."],
"16.2":["[[108^\\circ]].","They are equal.","Arrow markings.","They are parallel."],
"16.3":["[[180^\\circ]].","[[60^\\circ]].","8.","45."],
"16.4":["4.","3.","No, in general.","[[60^\\circ]]."],
"16.5":["Cylinder.","Triangle.","A plane that divides a solid into mirror-image halves.","The central axis joining the centres of the circular faces."],
"17.1":["350 cm.","2.5 kg.","100 cm.","1000 cm³."],
"17.2":["35 square units.","24 square units.","26 units.","[[A=bh]]."],
"17.3":["7 cm.","[[C=2\\pi r]].","[[A=\\pi r^2]].","[[10\\pi]]."],
"17.4":["[[1/4]].","[[280^\\circ]].","[[1/3]].","[[2\\pi r]]."],
"18.1":["Continuous.","Categorical.","20.","Two variables/categories at the same time."],
"18.2":["6.","5.","13.","Interquartile range."],
"18.3":["15.","105.","16.","Exact values inside each class are unknown."],
"18.4":["The second class.","3, 8, 12.","Around the 10th/11th values.","The exact individual data values."],
"18.5":["20.","20.","Frequency is a count; percentage is a proportion out of 100.","They allow fair comparison when totals differ."],
"18.6":["Range 5.","62.","12.","For example median and IQR."],
"18.7":["A sample is part of the population.","For example surveying only one top-set class.","No.","It is more affected by random variation."],
"19.1":["30.","[[1/5]].","Because the data are discrete/categorical.","A key."],
"19.2":["3.","Any evenly spaced scale covering the full range.","Two variables measured as pairs.","A point far from the main pattern."],
"19.3":["Positive.","Negative.","No.","Any plausible third variable affecting both."],
"19.4":["Prediction inside the observed data range.","Prediction outside the observed data range.","No.","The trend may not continue outside the observed range."],
"19.5":["4, 10, 13, 20.","The total frequency.","The upper class boundary.","No."],
"19.6":["40.","20.","13.","75th percentile."],
"19.7":["8.","3.","Frequency.","Yes."],
"19.8":["[[f=dw]].","3.","20.","8."],
"19.9":["11.","Because values read from a graph may be interpolated.","Their total sample sizes / what each sector represents.","Association shown by a graph does not establish cause."],
"19.10":["15.","IQR 6.","A higher typical value.","To make a valid like-for-like comparison."],
"19.11":["An axis that starts above/below its natural baseline, omitting part of the scale.","Prediction beyond the observed range.","The people chosen may not represent the population.","No; it can be appropriate if clearly labelled and not misleading."],
"20.1":["14.","The value fed into the function.","9.","[[x\\ne5]]."],
"20.2":["[[x=(y-2)/3]].","It reverses the original mapping.","No.","Otherwise one output could map back to more than one input."],
"20.3":["4.","f.","14.","So the whole substituted expression is treated as one input."],
"21.1":["Elements in A or B or both.","Elements in both A and B.","Elements not in A (within the universal set).","Because adding the set totals would otherwise count shared elements twice."],
"22.1":["2:3.","Direct proportion may be possible.","9 and 7.","[[\\propto]]."]
};